### ISSUE TITLE
Fix undifined windows object when page is compiled

### ISSUE THREAD

**Issue by carlosvicient** [carlosvicient/ntnu-idg3800-avgangsutstilling2022#13]
https://github.com/carlosvicient/ntnu-idg3800-avgangsutstilling2022/blob/9094897a027910b86497649115bfb62ba210bf5a/frontend/src/components/BackLink.jsx#L11

Many component have the same problem. The windows is only available in runtime (not when gatsby generates the pages). This should happen inside a hook

This also applies to other components.

**Comment by carlosvicient** [comment]
Hi, @icanseetime, can you code review this?

**Comment by glennispotatis** [comment]
Fix has been implemented
