### ISSUE TITLE
Consider improving this page

### ISSUE THREAD

**Issue by carlosvicient** [carlosvicient/ntnu-idg3800-avgangsutstilling2022#14]
https://github.com/carlosvicient/ntnu-idg3800-avgangsutstilling2022/blob/9094897a027910b86497649115bfb62ba210bf5a/frontend/src/components/ProjectList.jsx#L50

@icanseetime, I think you are in charge of code review, aren't you?

# Problem

Missing visual context? What is the section that shows pictures and text? (It's a summary of project...)

When a new project starts or ends? Maybe we need a title

![image](https://user-images.githubusercontent.com/10629868/161919533-f984c35e-b5d8-4a91-897b-6300f60cae07.png)

# Draft of a solution

![image](https://user-images.githubusercontent.com/10629868/161919861-2eb2b8ea-0d71-4db9-b69c-8f9ff15efb70.png)

Tentative code here (notice this is not finished, it is just an example: 34c8fc65cde701d0300abb8dc8a52e5ddac054a4

**Comment by carlosvicient** [comment]
@icanseetime, if this change is implemented, also notice BMED has not registred descriptive names for the projects. Therefore, someone needs to be notified to edit the project name.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/10629868/161921275-fe614bd5-9ead-476d-aeae-ee20ad54c3ea.png">

**Comment by glennispotatis** [comment]
Issue has been implemented
